### ISSUE TITLE
Update Fail

### ISSUE THREAD

**Issue by Bloodyaugust** [JuhaKiili/RagePixel#4]
All new update features fail to work correctly unless they are used immediately after importing a new sprite. Not a huge bug, but annoying.

**Comment by ericraue** [comment]
@Bloodyaugust I can't seem to reproduce this bug. Here's what I did:
1. Created a new spritesheet
2. Imported imgA as a new spriteA
3. Imported imgB as a new spriteB
4. Imported imgA as a new frame in spriteB
5. Modified imgA & imgB externally
6. Tried using each update function with no problems

What does the path point to? The path to the asset is displayed beside the Frame Index if it exists.

**Comment by Bloodyaugust** [comment]
My issue has been:
1. Import Sprite A
2. Externally modify Sprite A
3. Update functions do not work here, for any previous sprites either
4. Import another sprite, update before externally modifying anymore

**Comment by ericraue** [comment]
Okay I found the problem and was able to reproduce it. I needed to delete all my spritesheets first. Will try to test with a blank project from now on. The issue had to do with retrieving a cell from the atlas before the atlas was rebuilt for the first time. 

If this does not fix it please reopen the issue. Thanks for reporting it.

**Comment by Bloodyaugust** [comment]
Still having the same problem, with one twist: It got worse. Now, it doesn't update any sprites at all.

**Comment by ericraue** [comment]
I see what the problem was and I believe I fixed it. Basically it wasn't updating if there was no texture in the import texture field. When you apply the changes it should work with your existing sprites. If not check to see if there is an asset path beside the Frame Index. I'll leave this issue open for now so just close it if everything is fine. 

For future features I plan to test it in my project a bit more before committing. Just wanted to get this out quick for you since you asked.

**Comment by Bloodyaugust** [comment]
I'm comfortable calling this closed now, it works as far as I can tell. Thanks for getting it fixed so quickly!
